name: 'PMD Source Code Analyzer Action - Fix'
author: Jordan Pike - Forked from Mauricio Cano
description: 'This action allows to use PMD Source Code Analyzer from GitHub Actions and fixes a small issue with permissions'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'award'  
  color: 'red'
